// export const BASE_URL: string = "http://192.168.57.104:5500";
export const BASE_URL: string = "http://172.20.10.4:5500";
// export const BASE_URL: string = "http://localhost:5500";
export const AUTH_URL: string = "/api/v1/auth";
export const USERS_URL: string = "/api/v1/users";
export const CART_URL: string = "/api/v1/cart";
export const PRODUCT_URL: string = "/api/v1/product";
export const ORDER_URL: string = "/api/v1/order";
export const CATEGORY_URL: string = "/api/v1/category";
export const COUPON_URL: string = "/api/v1/coupon";
export const ADDRESS_URL: string = "/api/v1/address";
export const CHECKOUT_URL: string = "/api/v1/checkout";
export const WISHLIST_URL: string = "api/v1/wishlist"
